import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRef } from "react";

import { EXPERIENCES } from "@/constants/experiences";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const aboutMeRef = useRef<HTMLDivElement>(null);
  const experiencesRef = useRef<HTMLDivElement>(null);
  const projectsRef = useRef<HTMLDivElement>(null);

  const test = async () => {
    console.log("Everything works");
  };

  return (
    <>
      <Head>
        <title>Shahed Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles.left_side}>
            <div className={styles.header}>
              <h2 style={{ fontSize: "45px" }}>
                <a href={""}>Shahed Ahmed</a>
              </h2>
              <label>Software Engineer Intern</label>
              <p>System.out.println(&quot;Hello World&quot;);</p>
            </div>

            <div className={styles.sections}>
              <section>
                <a
                  href={"#about-me"}
                  onClick={() =>
                    aboutMeRef.current?.scrollIntoView({
                      behavior: "smooth",
                    })
                  }
                >
                  About Me
                </a>
              </section>
              <section>
                <a
                  href={"#experiences"}
                  onClick={() =>
                    experiencesRef.current?.scrollIntoView({
                      behavior: "smooth",
                    })
                  }
                >
                  Experiences
                </a>
              </section>
              {/* <section>
                <a
                  href={"#projects"}
                  onClick={() =>
                    projectsRef.current?.scrollIntoView({
                      behavior: "smooth",
                    })
                  }
                >
                  Projects
                </a>
              </section> */}
            </div>

            <div className={styles.links}>
              <a href={"https://github.com/Shahed4"} target={"_blank"}>
                <img
                  src={"github-icon.png"}
                  width={"30px"}
                  height={"30px"}
                ></img>
              </a>
              <a
                href={"https://www.linkedin.com/in/shahed-ahmed1/"}
                target={"_blank"}
              >
                <img src={"linkedin.png"} width={"30px"} height={"30px"}></img>
              </a>
            </div>
          </div>
          <div className={styles.right_side}>
            <div ref={aboutMeRef} className={styles.about_me}>
              <p>
                Hello! I&rsquo;m Shahed Ahmed, an enthusiastic software engineer
                with a keen interest in building web applications and machine
                learning. I am currently a junior attending The City College of
                New York pursuing a Bachelor&rsquo;s degree in Computer Science.
                My journey in the tech industry started with a simple curiosity
                in how phones and gaming systems worked.
              </p>
              <p>
                Throughout my studies, I&rsquo;ve developed strong skills in
                JavaScript, Python, Java, and C++, and have gained experience
                working with frameworks like React, Next.js, and Node.js.
              </p>
              <p>
                I&rsquo;m particularly passionate about backend development,
                where I enjoy designing and optimizing databases and ensuring
                the scalability and security of applications. My goal is to
                continue honing my backend skills and work on complex systems
                that require efficient data handling and robust architecture.
              </p>
              <p>
                When I’m not writing code, you can find me at the gym or
                strategizing my next chess move. I find these activities
                relaxing and allows me to stay balanced.I&rsquo;m always looking
                for new challenges and opportunities to grow, both
                professionally and personally.
              </p>
            </div>
            <div ref={experiencesRef} className={styles.experience}>
              {EXPERIENCES.map(({ role, company, time, description, link }) => (
                <a
                  className={styles.experience_card}
                  href={link}
                  target={"_blank"}
                  key={company}
                >
                  <div className={styles.time_frame}>
                    <p>{time}</p>
                  </div>
                  <div className={styles.experience_info}>
                    <h4>
                      {role} - {company}
                    </h4>
                    <p>{description}</p>
                  </div>
                </a>
              ))}
            </div>
            {/* <div ref={projectsRef} className={styles.projects}>
              <p>Under Construction</p>
            </div> */}
          </div>
        </main>
      </div>
    </>
  );
}
